B4J=true
Group=Handlers
ModulesStructureVersion=1
Type=Class
Version=10.5
@EndOfDesignText@
'Index handler
'Version: 4.00
Sub Class_Globals
	Private App As EndsMeet
	Private Path As String
	Private Method As String
	Private Request As ServletRequest
	Private Response As ServletResponse
End Sub

Public Sub Initialize
	App = Main.App
End Sub

Sub Handle (req As ServletRequest, resp As ServletResponse)
	Request = req
	Response = resp
	Path = Request.RequestURI
	Method = Request.Method.ToUpperCase
	If Path = "/" And Method = "GET" Then
		ShowIndexPage
	Else If Path = "/modal" Then
		If Method = "POST" Then
			ShowModal
		Else
			Response.SendError(405, "<h1>405 Method Not Allowed</h1>")
		End If
	Else
		Response.SendError(404, "<h1>404 Page Not Found</h1>")
	End If
End Sub

Private Sub ShowIndexPage
	App.WriteHtml2(Response, IndexPage.build, App.ctx)
End Sub

Public Sub IndexPage As MiniHtml
	Dim main1 As MainView
	main1.Initialize
	main1.LoadContent(ContainerContent)
	Dim page1 As MiniHtml = main1.Render
	'test prepend comment before head tag
	'Dim commment As String = " Generated by MiniHTML4 "
	'Dim cmt As MiniHtml = MH.CreateTag.text($"<!--${commment}-->"$)
	'page1.Children.InsertAt(0, cmt)
	Dim nav1 As Object = page1.ChildByClass("navbar-nav")
	If Initialized(nav1) Then
		MH.NavLinkItem("Home", "/", "bi bi-house me-2", "Home").up(nav1)
	End If
	If App.api.EnableHelp Then MH.NavLinkItem("API", "/help", "bi bi-gear me-2", "API").up(nav1)
	'Dim div1 As MiniHtml = page1.ChildByClass("bottom")
	'div1.comment(" bottom ")
	'Dim script1 As MiniHtml = page1.ChildByName("script")
	'script1.comment(" Scripts ")
	Dim head1 As MiniHtml = page1.ChildByName("head")
	head1.comment(" Generated by MiniHTML4 ")
	Dim body1 As MiniHtml = page1.ChildByName("body")
	body1.comment(" /Generated by MiniHTML4 ", "below")
	Return page1
End Sub

Private Sub ContainerContent As MiniHtml
    Dim div1 As MiniHtml = MH.Div
    div1.cls("d-flex align-items-center")
    'div1.sty("height: 100vh")
    Dim div2 As MiniHtml = MH.Div.up(div1)
    div2.sty("margin: auto")
    Dim div3 As MiniHtml = MH.Div.up(div2)
    div3.attr("id", "modals-here")
    div3.cls("modal modal-blur fade")
    div3.sty("display: none")
    div3.attr("aria-hidden", "false")
    div3.attr("tabindex", "-1")
    div3.wrapAttributes
    Dim div4 As MiniHtml = MH.Div.up(div3)
    div4.cls("modal-dialog modal-lg modal-dialog-centered")
    div4.attr("role", "document")
    Dim div5 As MiniHtml = MH.Div.up(div4)
    div5.cls("modal-content")
	Dim button1 As MiniHtml = MH.HxPost("/modal", "#modals-here", "")
    button1.attr("hx-trigger", "click")
    button1.attr("data-bs-toggle", "modal")
    button1.attr("data-bs-target", "#modals-here")
    button1.cls("btn btn-primary text-uppercase")
    button1.text("Open Modal")
    button1.wrapAttributes
	button1.multiline
	button1.up(div2)
	Return div1
End Sub

Private Sub Modal As MiniHtml
	Return MH.ContainerModalWithButton("Modal title", "Modal body text goes here.", "Close")
End Sub

Private Sub ShowModal
	App.WriteHtml(Response, Modal.build)
End Sub